language: erlang

os:
  - linux

otp_release:
   - 19.3
   - 20.3
   - 21.3
   - 22.3
   - 23.1

script:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3
  - ./rebar3 --version
  - erl -version
  - ./rebar3 test
  - ./rebar3 escriptize
  - _build/default/bin/elvis_core
