---
name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci:
    name: OTP ${{matrix.otp_vsn}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        otp_vsn: [23.3, 24.3, 25.0]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        id: setup-beam
        with:
          otp-version: ${{matrix.otp_vsn}}
          rebar3-version: '3.18'
      - name: Restore _build
        uses: actions/cache@v3
        with:
          path: _build
          key: "_build-cache-for\
                -os-${{runner.os}}\
                -otp-${{steps.setup-beam.outputs.otp-version}}\
                -rebar3-${{steps.setup-beam.outputs.rebar3-version}}\
                -hash-${{hashFiles('rebar.lock')}}"
      - name: Restore rebar3's cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/rebar3
          key: "rebar3-cache-for\
                -os-${{runner.os}}\
                -otp-${{steps.setup-beam.outputs.otp-version}}\
                -rebar3-${{steps.setup-beam.outputs.rebar3-version}}\
                -hash-${{hashFiles('rebar.lock')}}"
      - name: Compile
        run: ERL_FLAGS="-enable-feature all" rebar3 compile
      - name: Format check
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: ERL_FLAGS="-enable-feature all" rebar3 format --verify
      - name: Run test
        run: ERL_FLAGS="-enable-feature all" rebar3 test
      - name: Run elvis on elvis
        run: |
          ERL_FLAGS="-enable-feature all" rebar3 escriptize
          ERL_FLAGS="-enable-feature all" _build/default/bin/elvis_core
